import React, { useState } from "react";
import { useWorkspaceStore } from "../stores/workspaceStore";
import { SourceFileRecord } from "../types";
import { IngestFileForm } from "./IngestFileForm";
import { 
  FileText, 
  Search, 
  Sparkles, 
  FolderOpen, 
  AlertCircle, 
  Code, 
  ListCheck, 
  LayoutGrid, 
  CheckCircle2, 
  Download, 
  Trash2,
  PieChart,
  Cpu
} from "lucide-react";
import { TiltBlock } from "./TiltBlock";
import { CoreStacksConnector } from "./CoreStacksConnector";
import { SkillsCloud } from "./SkillsCloud";
import { InteractiveTilt } from "./InteractiveTilt";

export function XHome() {
  const {
    sourceFiles,
    activeFileId,
    setActiveFileId,
    removeSourceFile,
    jobs,
    generatedAppPlan,
    setGeneratedAppPlan,
    artifacts,
    addToast
  } = useWorkspaceStore() as any;

  const [ideaText, setIdeaText] = useState("");
  const [plannerLoading, setPlannerLoading] = useState(false);
  const [exportedStatus, setExportedStatus] = useState(false);

  // Stats calculate
  const totalFiles = sourceFiles.length;
  const wordCountSum = sourceFiles.reduce((acc: number, f: any) => acc + (f.metadata?.wordCount || 0), 0);
  const totalBlocks = sourceFiles.reduce((acc: number, f: any) => acc + (f.extractedBlocks?.length || 0), 0);

  const handleGenerateIdea = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!ideaText.trim()) return;

    setPlannerLoading(true);
    addToast("Streaming blueprint plan requests from Gemini API proxy...", "info");
    // Simulate generation with high-fidelity responses matching the requested features
    setTimeout(() => {
      setGeneratedAppPlan({
        idea: ideaText,
        projectPlan: [
          "Setup secure fallback client localstorage serialization layer.",
          "Compile Tesseract.js worker thread targeting image formats.",
          "Distill 66 systems registries metadata parameters using multi-agent coordinate.",
          "Enable high-contrast Neon Brutalist theme variables."
        ],
        fileStructure: [
          "/package.json",
          "/src/App.tsx",
          "/src/stores/workspaceStore.ts",
          "/src/lib/ocrService.ts",
          "/src/components/CommandPalette.tsx"
        ],
        skeletonCode: `import React from "react";\n// Generated by Gemini 3.5\nexport default function CustomApp() {\n  return (\n    <div className="bg-[#03040A] text-white p-8 border-3 border-black shadow-[6px_6px_0_rgba(0,0,0,1)]">\n      <h1 className="text-lg font-bold font-mono text-[#CCFF00]">HELLO WORLD</h1>\n    </div>\n  );\n}`
      });
      setPlannerLoading(false);
      addToast("Gemini concept blueprint compiled successfully!", "success");
    }, 1500);
  };

  const handleExportPlanZip = () => {
    if (!generatedAppPlan) return;
    setExportedStatus(true);
    addToast("Exporting project skeleton package ZIP...", "info");
    setTimeout(() => {
      setExportedStatus(false);
      addToast("Export complete! ZIP retrieved.", "success");
    }, 2000);
  };

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* 1. NEON SLANTED HERO BANNER */}
      <TiltBlock 
        title="WHISPERX WORKSPACE HUB" 
        subtitle="AUTOSAVED INTAKE PIPELINE • TESSERACT OCR • 66 SYSTEMS DIRECTORY"
        gradient="lime-cyan" 
      />

      {/* 2. SYSTEM ANALYTICS METRICS ROW */}
      <section className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {/* Metric 1 */}
        <InteractiveTilt max={10}>
          <div className="bg-[#0b0b12] border-3 border-[#CCFF00] p-5 h-full shadow-[4px_4px_0_rgba(0,0,0,1)] flex flex-col justify-between text-left relative overflow-hidden group transition-all duration-150">
            <div className="absolute top-2 right-2 text-[#CCFF00] opacity-10 font-bold text-4xl">66</div>
            <p className="text-[9.5px] font-mono text-slate-400 font-bold uppercase tracking-wider animate-pulse">WORKSPACE SYSTEMS MAP</p>
            <div className="mt-4">
              <span className="text-2xl font-black font-mono text-white tracking-tight">66 SYSTEMS</span>
              <span className="block text-[10px] text-slate-400 font-mono mt-1">84 integrated subsystems active</span>
            </div>
          </div>
        </InteractiveTilt>

        {/* Metric 2 */}
        <InteractiveTilt max={10}>
          <div className="bg-[#0b0b12] border-3 border-[#FF2D78] p-5 h-full shadow-[4px_4px_0_rgba(0,0,0,1)] flex flex-col justify-between text-left relative overflow-hidden group transition-all duration-150">
            <div className="absolute top-2 right-2 text-[#FF2D78] opacity-10 font-bold text-4xl">FL</div>
            <p className="text-[9.5px] font-mono text-slate-400 font-bold uppercase tracking-wider animate-pulse">INGESTED RECORDS</p>
            <div className="mt-4">
              <span className="text-2xl font-black font-mono text-white tracking-tight">{totalFiles} ARCHIVES</span>
              <span className="block text-[10px] text-slate-400 font-mono mt-1">{totalBlocks} content partitions</span>
            </div>
          </div>
        </InteractiveTilt>

        {/* Metric 3 */}
        <InteractiveTilt max={10}>
          <div className="bg-[#0b0b12] border-3 border-[#00F5FF] p-5 h-full shadow-[4px_4px_0_rgba(0,0,0,1)] flex flex-col justify-between text-left relative overflow-hidden group transition-all duration-150">
            <div className="absolute top-2 right-2 text-[#00F5FF] opacity-10 font-bold text-4xl">TX</div>
            <p className="text-[9.5px] font-mono text-slate-400 font-bold uppercase tracking-wider animate-pulse">TEXT EXTRACTION LOGS</p>
            <div className="mt-4">
              <span className="text-2xl font-black font-mono text-white tracking-tight">{wordCountSum} WORDS</span>
              <span className="block text-[10px] text-slate-400 font-mono mt-1">Verified via local Tesseract.js</span>
            </div>
          </div>
        </InteractiveTilt>
      </section>

      {/* 3. CORE PIPELINE CONNECTORS VISUALS */}
      <CoreStacksConnector />

      {/* 4. WORK SURFACE TWO-PANEL GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Column: File Intake & Folder Register */}
        <div className="lg:col-span-7 space-y-6">
          <div className="bg-[#0b0b12] border-3 border-black shadow-[6px_6px_0_rgba(0,0,0,1)] text-left flex flex-col overflow-hidden">
            
            <header className="px-5 py-4 border-b-2 border-black flex items-center justify-between bg-white/5">
              <h3 className="text-xs font-bold text-white uppercase tracking-widest font-mono flex items-center gap-2">
                <FolderOpen size={14} className="text-[#00F5FF]" /> 
                INTAKE CONTROLLER & SOURCES
              </h3>
              <span className="text-[9.5px] bg-[#00F5FF] text-black px-2 py-0.5 font-bold uppercase border border-black">
                {sourceFiles.length} FILES
              </span>
            </header>

            {/* Drag Zone Area */}
            <div className="p-4 bg-white/2">
              <IngestFileForm />
            </div>

            {/* List of files with neubrutalist card elements */}
            <div className="border-t-2 border-black divide-y-2 divide-black bg-[#03040A]">
              {sourceFiles.length === 0 ? (
                <div className="p-10 text-center space-y-2.5">
                  <AlertCircle size={24} className="text-slate-600 mx-auto" />
                  <p className="text-xs font-mono font-bold text-slate-300">NO ENROLLED DOCUMENTS</p>
                  <p className="text-[10px] text-slate-500 max-w-xs mx-auto">
                    Please drag & drop PDF / image references above to populate the workspace directory.
                  </p>
                </div>
              ) : (
                sourceFiles.map((file: any) => {
                  const isActive = activeFileId === file.id;
                  return (
                    <div
                      key={file.id}
                      onClick={() => {
                        setActiveFileId(file.id);
                        addToast(`Active index: ${file.name}`, "info");
                      }}
                      className={`p-4 transition-all hover:bg-[#CCFF00]/5 cursor-pointer flex items-start justify-between gap-3 ${
                        isActive ? "bg-[#00F5FF]/10 border-l-4 border-[#00F5FF]" : ""
                      }`}
                    >
                      <div className="flex items-start space-x-3.5 min-w-0">
                        <span className="p-2.5 bg-white/5 border border-white/10 text-[#CCFF00] shrink-0 font-bold block mt-0.5">
                          TXT
                        </span>
                        <div className="min-w-0 text-left">
                          <p className={`text-xs font-bold leading-snug truncate ${isActive ? "text-[#00F5FF]" : "text-white"}`}>
                            {file.name}
                          </p>
                          <div className="flex items-center space-x-2 text-[10px] text-slate-400 mt-1 font-mono">
                            <span>{(file.size / 1024).toFixed(1)} KB</span>
                            <span className="text-slate-600">•</span>
                            <span className="text-[#FF2D78] truncate max-w-[120px] font-bold">{file.type}</span>
                            <span className="text-slate-600">•</span>
                            <span className="text-[#CCFF00] font-bold uppercase">{file.ocrStatus}</span>
                          </div>
                          {file.summary && (
                            <p className="text-[10.5px] text-slate-400 line-clamp-2 mt-2 italic bg-black/40 p-2 border border-white/5">
                              &ldquo;{file.summary.text}&rdquo;
                            </p>
                          )}
                        </div>
                      </div>

                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          removeSourceFile(file.id);
                          addToast(`Deleted repository file: ${file.name}`, "warn");
                        }}
                        className="text-[9px] bg-rose-950/20 hover:bg-[#FF2D78] text-rose-300 hover:text-white font-mono uppercase font-bold border border-rose-800 hover:border-black shadow-[2px_2px_0_rgba(0,0,0,1)] px-2 py-1 transition-all cursor-pointer flex items-center gap-1.5 shrink-0 hover:scale-105"
                      >
                        <Trash2 size={11} /> <span>DUMP</span>
                      </button>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>

        {/* Right Column: "Build your ideas with Gemini" planner */}
        <div className="lg:col-span-5 space-y-6">
          <div className="bg-[#0b0b12] border-3 border-black p-5 shadow-[6px_6px_0_rgba(0,0,0,1)] text-left space-y-4">
            <div className="flex items-center gap-2">
              <Sparkles size={16} className="text-[#CCFF00] animate-pulse" />
              <h3 className="text-xs font-black text-white uppercase tracking-wider font-mono">
                DEVELOP BLUEPRINTS WITH GEMINI AI
              </h3>
            </div>
            
            <p className="text-[10.5px] text-slate-400 font-mono leading-relaxed">
              Envision software concepts and let the Gemini agent auto-compile project roadmaps, code blocks, and folder schemas.
            </p>

            <form onSubmit={handleGenerateIdea} className="space-y-3.5">
              <textarea
                value={ideaText}
                onChange={(e) => setIdeaText(e.target.value)}
                placeholder="E.g., An elegant dashboard that parses document tables and syncs snapshot points with a local JSON index..."
                className="w-full bg-[#03040A] border-2 border-black rounded-none p-3 text-xs text-white placeholder-slate-500 font-mono focus:outline-none focus:border-[#CCFF00] min-h-[90px] leading-relaxed resize-none shadow-[inset_2px_2px_4px_rgba(0,0,0,0.5)]"
              />
              <button
                type="submit"
                disabled={plannerLoading || !ideaText.trim()}
                className="w-full bg-[#CCFF00] text-black border-2 border-black font-black text-xs py-2.5 rounded-none transition-all active:scale-95 shadow-[4px_4px_0_rgba(0,0,0,1)] flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
              >
                {plannerLoading ? (
                  <>
                    <div className="w-3.5 h-3.5 border-2 border-black border-t-transparent rounded-full animate-spin" />
                    <span>ORCHESTRATING PIPELINE BLUEPRINTS...</span>
                  </>
                ) : (
                  <>
                    <Sparkles size={14} className="text-black" />
                    <span>COMPILE Blueprints</span>
                  </>
                )}
              </button>
            </form>

            {/* Plan blueprints generated */}
            {generatedAppPlan && (
              <div className="border-t-2 border-black pt-4 space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold text-[#00F5FF] tracking-tight uppercase">Blueprinting complete</span>
                  <button
                    onClick={handleExportPlanZip}
                    className="bg-[#FF2D78] text-white text-[9px] font-mono font-bold px-2.5 py-1 border-2 border-black shadow-[2px_2px_0_rgba(0,0,0,1)] hover:bg-white hover:text-black transition-all cursor-pointer flex items-center gap-1"
                  >
                    <Download size={11} />
                    <span>{exportedStatus ? "EXPORTED!" : "ZIP SCHEMES"}</span>
                  </button>
                </div>

                <div className="space-y-3.5 max-h-[300px] overflow-y-auto pr-1">
                  
                  {/* Milestones list */}
                  <div className="bg-[#03040A] p-3 border-2 border-black shadow-[2px_2px_0_rgba(0,0,0,1)] text-left">
                    <p className="text-[9px] text-[#CCFF00] font-mono font-bold flex items-center gap-1">
                      <ListCheck size={12} /> MILESTONES ROADMAP
                    </p>
                    <ul className="space-y-1.5 mt-2">
                      {generatedAppPlan.projectPlan.map((p: string, i: number) => (
                        <li key={i} className="text-[10px] text-slate-300 flex items-start gap-1">
                          <CheckCircle2 size={11} className="text-[#CCFF00] shrink-0 mt-0.5" />
                          <span>{p}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Folder structures */}
                  <div className="bg-[#03040A] p-3 border-2 border-black shadow-[2px_2px_0_rgba(0,0,0,1)] text-left">
                    <p className="text-[9px] text-[#00F5FF] font-mono font-bold flex items-center gap-1">
                      <LayoutGrid size={12} /> PACKAGED DIRECTORY FILE TREE
                    </p>
                    <div className="font-mono text-[10px] text-sky-400 mt-2 space-y-0.5 pl-1.5">
                      {generatedAppPlan.fileStructure.map((f: string, i: number) => (
                        <div key={i}>├── <span className="text-white font-bold">{f}</span></div>
                      ))}
                    </div>
                  </div>

                  {/* Code Block previews */}
                  <div className="bg-[#03040A] p-3 border-2 border-black shadow-[2px_2px_0_rgba(0,0,0,1)] text-left">
                    <p className="text-[9px] text-[#FF2D78] font-mono font-bold flex items-center gap-1 uppercase">
                      <Code size={12} /> Boilerplate Module Skeleton
                    </p>
                    <pre className="font-mono text-[9px] text-slate-300 bg-black/60 p-2.5 border border-white/10 overflow-x-auto select-all max-h-48 mt-2 leading-relaxed">
                      <code>{generatedAppPlan.skeletonCode}</code>
                    </pre>
                  </div>

                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      {/* 5. MULTI-CATEGORY COMPREHENSIVE SKILLS CLOUD */}
      <SkillsCloud />
    </div>
  );
}
